import { Item } from './types';

export const MOCK_ITEMS: Item[] = [
  {
    id: '1',
    listingTitle: 'Old dusty film camera',
    realTitle: 'Contax T2 Silver',
    listingPrice: 150,
    realValue: 1200,
    confidenceScore: 92,
    marketplace: 'FB Marketplace',
    imageUrl: 'https://picsum.photos/id/250/600/600',
    category: 'Cameras',
    listingDate: '2 hours ago',
    condition: 'Used',
    description: 'Found this in my grandpas attic. Don\'t know if it works. Sold as is.',
    matchReason: 'Visual match on lens configuration and titanium finish despite vague description.'
  },
  {
    id: '2',
    listingTitle: 'Mid century office chair mesh',
    realTitle: 'Herman Miller Aeron (Classic)',
    listingPrice: 50,
    realValue: 450,
    confidenceScore: 88,
    marketplace: 'Craigslist',
    imageUrl: 'https://picsum.photos/id/1060/600/600', // Using a generic interior shot
    category: 'Furniture',
    listingDate: '1 day ago',
    condition: 'Good',
    description: 'Comfortable office chair. Mesh back. Moving out sale.',
    matchReason: 'Distinctive pellicle mesh pattern and lumbar support shape identified.'
  },
  {
    id: '3',
    listingTitle: 'Vintage colorful sweater 90s',
    realTitle: 'Coogi Authentic Australian Knit',
    listingPrice: 40,
    realValue: 350,
    confidenceScore: 75,
    marketplace: 'Vinted',
    imageUrl: 'https://picsum.photos/id/103/600/600',
    category: 'Clothing',
    listingDate: '4 hours ago',
    condition: 'Excellent',
    description: 'Funky pattern sweater. Size L. Very warm.',
    matchReason: 'Mercerized cotton texture and chaotic 3D knit pattern characteristic of Coogi.'
  },
  {
    id: '4',
    listingTitle: 'Heavy japanese pans',
    realTitle: 'Le Creuset Enameled Cast Iron Set',
    listingPrice: 80,
    realValue: 400,
    confidenceScore: 95,
    marketplace: 'FB Marketplace',
    imageUrl: 'https://picsum.photos/id/450/600/600',
    category: 'Kitchen',
    listingDate: 'Just now',
    condition: 'Fair',
    description: 'Three orange pots. Heavy. Cleaning out the garage.',
    matchReason: 'Signature Volcanic Orange gradient and three-ring lid design detected.'
  },
  {
    id: '5',
    listingTitle: 'Retro gaming box nintendo',
    realTitle: 'GameCube Panasonic Q',
    listingPrice: 200,
    realValue: 900,
    confidenceScore: 82,
    marketplace: 'eBay',
    imageUrl: 'https://picsum.photos/id/96/600/600',
    category: 'Electronics',
    listingDate: '3 days ago',
    condition: 'Broken',
    description: 'Shiny silver gamecube thing. Doesnt turn on.',
    matchReason: 'Chrome finish and DVD drive tray indicate rare Panasonic Q variant.'
  },
  {
    id: '6',
    listingTitle: 'Old leather lounge chair',
    realTitle: 'Eames Lounge Chair & Ottoman (Replica or Real)',
    listingPrice: 500,
    realValue: 4500,
    confidenceScore: 45, // Lower confidence because replicas are common
    marketplace: 'Craigslist',
    imageUrl: 'https://picsum.photos/id/1078/600/600',
    category: 'Furniture',
    listingDate: '5 hours ago',
    condition: 'Worn',
    description: 'Black leather chair with wood shell. Need it gone.',
    matchReason: 'Shock mount placement suggests authentic Vitra/Herman Miller production.'
  },
  {
    id: '7',
    listingTitle: 'Blurry synthesizer keyboard',
    realTitle: 'Roland Juno-106',
    listingPrice: 300,
    realValue: 1800,
    confidenceScore: 89,
    marketplace: 'FB Marketplace',
    imageUrl: 'https://picsum.photos/id/454/600/600',
    category: 'Music',
    listingDate: '10 mins ago',
    condition: 'Good',
    description: 'Old keyboard from the 80s. Works fine.',
    matchReason: 'Control panel layout and colorful slider caps match Juno-106 exactly.'
  },
  {
    id: '8',
    listingTitle: 'Designer lamp',
    realTitle: 'Artemide Tolomeo Mega',
    listingPrice: 75,
    realValue: 800,
    confidenceScore: 91,
    marketplace: 'Vinted',
    imageUrl: 'https://picsum.photos/id/439/600/600',
    category: 'Furniture',
    listingDate: '1 day ago',
    condition: 'Like New',
    description: 'Tall floor lamp. Aluminum.',
    matchReason: 'Cantilever mechanism and parchment shade texture are consistent with Artemide.'
  }
];
